### ISSUE TITLE
AI.BPANN

### ISSUE THREAD

**Issue by hqm42** [saschagrunert/nn#1]
Looks a lot like what I wrote 7 years ago:
https://hackage.haskell.org/package/bpann-0.1.1/docs/AI-BPANN.html
Thank you for adding specs ;)

**Comment by saschagrunert** [comment]
Yes it was the base. I hope we can further improve it if you’re willing to. :)

**Comment by saschagrunert** [comment]
I will close this because there seems nothing to do here.
